# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_unpaiduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(default='Padwan', max_length=50),
        ),
    ]
